### ISSUE TITLE
task_for_pid failed with error code : 5

### ISSUE THREAD

**Issue by bavaria95** [n1nj4sec/memorpy#12]
OS X, python 2.7.13, memorpy 1.7

```python
mw=MemWorker(pid=42723)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/memorpy/MemWorker.py", line 35, in __init__
    self.process = Process.Process(name=name, pid=pid, debug=debug)
  File "/usr/local/lib/python2.7/site-packages/memorpy/OSXProcess.py", line 67, in __init__
    self._open()
  File "/usr/local/lib/python2.7/site-packages/memorpy/OSXProcess.py", line 81, in _open
    raise ProcessException("task_for_pid failed with error code : %s"%ret)
memorpy.BaseProcess.ProcessException: task_for_pid failed with error code : 5
```

**Comment by n1nj4sec** [comment]
you are probably missing some privileges

> The task_for_pid system call is protected by the gatekeeper security framework, and will fail (with error code 5, KERN_FAILURE) unless the calling process is digitally signed, and its Info.plist includes the SecTaskAccess 
cf. https://www.spaceflint.com/?p=150

**Comment by bavaria95** [comment]
@n1nj4sec, I even didn't have an idea to run python with `sudo`. It helped. Thanks! :)
