### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by MikulasZelinka** [n1nj4sec/memorpy#16]
Hello,

are you planning on supporting Python 3, please?

If I wanted to try to make it work in Python 3, was there any particular problem why Python 3 that you've encountered (e.g. are there some dependencies which also don't support it)?

Thanks :)

**Comment by n1nj4sec** [comment]
Hello,
You should be fine there is no dependencies in this project, everything is implemented in ctypes

**Comment by Mehodin** [comment]
https://mehodin.com/i/9447dcac.png <- Getting that error tho, how to fix?

**Comment by matslindh** [comment]
There's a set of fixes necessary (imports, print-statements, fixing setup.py, handling bytes vs strings) to get memorpy to run properly under python3, but I have a version running. I'll make a PR in a day or two - but I've only tested it under Windows. 

As there seems to be no tests available I can't confirm that I haven't broken something outside of the functions I'm using myself.

**Comment by matslindh** [comment]
I've added PR#20 as an initial set of fixes to make memorpy work under Python 3. Since my usage was limited to Windows this time, I haven't tested the patch with other OS-es or that it is in any way backwards compatible with Python 2.

**Comment by JackofSpades707** [comment]
it appears #20 doesn't work  on linux, or at least my ArchLinux WSL installation
not sure if the problem would persist on a native linux install or not

```
>>> from memorpy import *

>>> mw = MemWorker(pid=4368) # Yes the pid is a WSL process
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/Admin/Desktop/code/pyantidote/pyantidote/memorpy/MemWorker.py", line 35, in __init__
    self.process = Process.Process(name=name, pid=pid, debug=debug)
  File "/mnt/c/Users/Admin/Desktop/code/pyantidote/pyantidote/memorpy/LinProcess.py", line 87, in __init__
    self._open()
  File "/mnt/c/Users/Admin/Desktop/code/pyantidote/pyantidote/memorpy/LinProcess.py", line 157, in _open
    path=create_string_buffer("/proc/" + str(self.pid) + "/mem")
  File "/usr/lib/python3.7/ctypes/__init__.py", line 63, in create_string_buffer
    raise TypeError(init)
TypeError: /proc/4368/mem

/proc/4368/mem
```
