### ISSUE TITLE
OSXProcess.pid_from_name failing to find process IDs

### ISSUE THREAD

**Issue by javakat** [n1nj4sec/memorpy#21]
When attempting to fetch memory on mac OS like so:

``` python
from memorpy import MemWorker

application_name = "OpenEmu"

memory_worker = MemWorker(name=application_name)

search_results = [x for x in memory_worker.mem_search(36)]
```

I received the following consistent traceback:

```
Traceback (most recent call last):
  File "reader-prototype.py", line 5, in <module>
    memory_worker = MemWorker(name=application_name)
  File "/Users/milieu/Projects/read-snes/venv/lib/python2.7/site-packages/memorpy/MemWorker.py", line 35, in __init__
    self.process = Process.Process(name=name, pid=pid, debug=debug)
  File "/Users/milieu/Projects/read-snes/venv/lib/python2.7/site-packages/memorpy/OSXProcess.py", line 62, in __init__
    self.pid=OSXProcess.pid_from_name(name)
  File "/Users/milieu/Projects/read-snes/venv/lib/python2.7/site-packages/memorpy/OSXProcess.py", line 101, in pid_from_name
    if name in dic['exe']:
KeyError: 'exe'
```

**Comment by SJS830** [comment]
This error can be fixed by changing this line: `if name in dic['exe']:` to `if name in dic['name']:`
